import Header from '../components/globals/header';
import Footer from '../components/globals/footer';
import { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  icons: {
     icon: "/Logo.svg"
  },
  title: "100 KARMA",
  description: "Generated by KARMA",
};


export default function RootLayout({
  children,
} : {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#20282F]'>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}