import '../styles/globals.css'
import Head from './head';
import Header from '../components/globals/header';
import Footer from '../components/globals/footer';
// import Signup from './signup/page';

export default function RootLayout({
  children,
} : {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head/>
      <body className='bg-[#20282F]'>
        <Header/>
        {/* <Signup/> */}
        {children}
        <Footer/>
      </body>
    </html>
  )
}





// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import './globals.css'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }
